@extends('layouts.main')

@section('content')
<div class="content-text">
  <p>
    LOREM IPSUM DOLOR SIT AMET, CONSECTETUR ADIPISCING ELIT. UT DICTUM DUI AC RUTRUM ULTRICES. SUSPENDISSE MALESUADA EX AC NISI RUTRUM CONSEQUAT. SUSPENDISSE POTENTI. VESTIBULUM TELLUS METUS, ELEIFEND VITAE TURPIS TRISTIQUE, RHONCUS VIVERRA NISI. QUISQUE QUIS ENIM EUISMOD, SOLLICITUDIN MAURIS QUIS, FINIBUS DOLOR. SUSPENDISSE A SAPIEN A RISUS SEMPER CONSEQUAT. CRAS IMPERDIET ULTRICES ODIO, A CONSECTETUR NUNC LACINIA SED. CURABITUR FACILISIS ORNARE NISL, QUIS TINCIDUNT LACUS GRAVIDA EGET. INTEGER ID TORTOR EGET TELLUS TEMPUS TRISTIQUE NON SIT AMET EST. PRAESENT ID PRETIUM TORTOR. SED SCELERISQUE, TURPIS ET DICTUM ELEMENTUM, MASSA LACUS ACCUMSAN MAURIS, SED CONGUE EROS LEO NON SAPIEN.
  </p>
  <p>
    NAM UT PELLENTESQUE JUSTO, EU TEMPOR LOREM. ALIQUAM AUGUE ERAT, FEUGIAT NON AUCTOR EU, LACINIA AC DOLOR. AENEAN QUIS NISL TORTOR. PHASELLUS ET DOLOR UT DIAM ALIQUAM DICTUM. VESTIBULUM LIBERO RISUS, TINCIDUNT A VOLUTPAT SED, AUCTOR QUIS EST. SUSPENDISSE NON VENENATIS DUI. PELLENTESQUE PULVINAR VIVERRA LEO, AT IMPERDIET URNA TEMPUS NEC. NAM ID TINCIDUNT MI, UT DIGNISSIM TORTOR. PROIN MOLESTIE EGET ARCU EGET MAXIMUS. QUISQUE ELEMENTUM IN ENIM ID VIVERRA. IN FAUCIBUS GRAVIDA ELIT, VITAE VARIUS NUNC ALIQUAM UT. PHASELLUS NISL ERAT, EUISMOD UT CONVALLIS IN, PRETIUM QUIS TELLUS. SED NEC SEM ELEIFEND MAURIS ULTRICES FACILISIS.
  </p>
  <p><a href="#" class="uk-button lage-button-ameete uk-button-secondary uk-width-1-1">WHERE TO BUY</a></p>
</div>
@endsection
